version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
    include: scope

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
    include: scope
  groups:
    kubernetes:
      patterns:
        - "k8s.io/*"
